name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t flask-app .

      - name: Run Docker container
        run: docker run -d -p 5000:5000 flask-app

      - name: Verify Docker running containers
        run: docker ps

      - name: Wait until service is available
        run: |
          for i in {1..10}; do
            curl -f http://localhost:5000 && break
            echo "Waiting for the service..."
            sleep 5
          done

      - name: Test the app
        run: curl -f http://localhost:5000
      
      - name: Stop all containers
        run: docker stop $(docker ps -q)
